In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from math import log
from numpy.linalg import *
from scipy.stats.distributions import chi2

data1 = pd.read_excel("心电图.xlsx")

In [2]:
A = data1[0:-1]
A

编号      X1     X2  g
0    1  261.01   7.36  1
1    2  185.39   5.99  1
2    3  249.58   6.11  1
3    4  137.13   4.35  1
4    5  231.34   8.79  1
5    6  231.38   8.53  1
6    7  260.25  10.02  1
7    8  259.51   9.79  1
8    9  273.84   8.79  1
9   10  303.59   8.53  1
10  11  231.03   6.15  1
11  12  308.90   8.49  2
12  13  258.69   7.16  2
13  14  355.54   9.43  2
14  15  476.69  11.32  2
15  16  316.12   8.17  2
16  17  274.57   9.67  2
17  18  409.42  10.49  2
18  19  330.34   9.61  3
19  20  331.47  13.72  3
20  21  352.50  11.00  3
21  22  347.31  11.19  3
22  23  189.59   5.46  3

In [3]:
B = np.array(data1[-1:])[0][1:-1]
B

array([380.2, 9.08], dtype=object)

In [4]:
g1 = A[0:11]
g2 = A[11:18]
g3 = A[18:]

In [5]:
g1["X1"].values

array([261.01, 185.39, 249.58, 137.13, 231.34, 231.38, 260.25, 259.51,
       273.84, 303.59, 231.03])

In [6]:
n = 23
k = 3
p = 2
n1 = 11
n2 = 7
n3 = 5
f = p*(p+1)*(k-1)/2
d = (2*pow(p, 2)+3*p-1)*(1/(n-1)+1/(n2-1)+1/(n3-1)-1/(n-k))/(6*(p+1)*(k-1))
p1 = n1/n
p2 = n2/n
p3 = n3/n
m1 = np.mean(g1)
m2 = np.mean(g2)
m3 = np.mean(g3)
s1 = np.cov(np.array(g1["X1"]),np.array(g1["X2"]))
s2 = np.cov(np.array(g2["X1"]),np.array(g2["X2"]))
s3 = np.cov(np.array(g3["X1"]),np.array(g3["X2"]))
s = ((n1-1)*s1+(n2-1)*s2+(n3-1)*s3)/(n-k)

In [7]:
s

array([[3748.64995114,   92.94790414],
       [  92.94790414,    4.08295587]])

In [8]:
M = (n-k)*log(det(s))-((n1-1)*log(det(s1))+(n2-1)*log(det(s2))+(n3-1)*log(det(s3)))
T = (1-d)*M

In [9]:
C = chi2.ppf(0.95, f)
if T < C:
    print("协方差相等")
else:
    print("协方差不相等")

协方差相等


In [10]:
x = B
x

array([380.2, 9.08], dtype=object)

In [11]:
m1 = [m1.loc["X1"],m1.loc["X2"]]
m2 = [m2.loc["X1"],m2.loc["X2"]]
m3 = [m3.loc["X1"],m3.loc["X2"]]

In [12]:
tp1 = m1*inv(s)*x-m1*inv(s)*np.array(m1).reshape(1,2)/2+log(p1)
tp2 = m2*inv(s)*x-m2*inv(s)*np.array(m2).reshape(1,2)/2+log(p2)
tp3 = m3*inv(s)*x-m3*inv(s)*np.array(m3).reshape(1,2)/2+log(p3)

In [13]:
tps = np.array([tp1, tp2, tp3])
tps

array([[[37.38544655413162, -1.2985868805422092],
        [-868.6032558895082, 21.88741260029191]],

       [[42.65081240199972, -1.7641659214973466],
        [-999.2099149709402, 21.983679075795074]],

       [[41.24283998157414, -2.0921501998409644],
        [-975.1538393718353, 21.304881913442273]]], dtype=object)

In [14]:
# 类别
i = 1
for tp in tps:
    if tp.all() == np.max(tps.all(), axis = 0):
        print(i)
    i += 1

3
