In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing

plt.rcParams['font.sans-serif'] = ['SimHei'] 
plt.rcParams['axes.unicode_minus'] = False 

data1 = pd.read_csv('2.csv', encoding='gbk')

In [2]:
data1 = data1.set_index(['样本序号'])
data1

x1：人口密度(人/km2)  x 2：人均耕地面积(ha)  x 3：森林覆盖率(%)  x 4：农民人均纯收入(元/人)  \
样本序号                                                                   
1            363.912           0.352        16.101            192.11   
2            141.503           1.684        24.301           1752.35   
3            100.695           1.067        65.601           1181.54   
4            143.739           1.336        33.205           1436.12   
5            131.412           1.623        16.607           1405.09   
6             68.337           2.032        76.204           1540.29   
7             95.416           0.801        71.106            926.35   
8             62.901           1.652        73.307           1501.24   
9             86.624           0.841        68.904            897.36   
10            91.394           0.812        66.502            911.24   
11            76.912           0.858        50.302            103.52   
12            51.274           1.041        64.609            968.33   
13            68.831           0.836        62.804            957.14   
14            77.301           0.623        60.102            824.37   
15            76.948           1.022        68.001           1255.42   
16            99.265           0.654        60.702           1251.03   
17           118.505           0.661        63.304           1246.47   
18           141.473           0.737        54.206            814.21   
19           137.761           0.598        55.901           1124.05   
20           117.612           1.245        54.503            805.67   
21           122.781           0.731        49.102           1313.11   

      x 5：人均粮食产量 (kg/人)  x 6：经济作物占农作物播面比例(％)  x 7：耕地占土地面积比率(％)  \
样本序号                                                             
1                295.34               26.724            18.492   
2                452.26               32.314            14.464   
3                270.12               18.266             0.162   
4                354.26               17.486            11.805   
5                586.59               40.683            14.401   
6                216.39                8.128             4.065   
7                291.52                8.135             4.063   
8                225.25               18.352             2.645   
9                196.37               16.861             5.176   
10               226.51               18.279             5.643   
11               217.09               19.793             4.881   
12               181.38                4.005             4.066   
13               194.04                9.110             4.484   
14               188.09               19.409             5.721   
15               211.55               11.102             3.133   
16               220.91                4.383             4.615   
17               242.16               10.706             6.053   
18               193.46               11.419             6.442   
19               228.44                9.521             7.881   
20               175.23               18.106             5.789   
21               236.29               26.724             7.162   

      x 8：果园与林地面积之比(％)  x 9：灌溉田占耕地面积之比(％)  
样本序号                                       
1                2.231             26.262  
2                1.455             27.066  
3                7.474             12.489  
4                1.892             17.534  
5                0.303             22.932  
6                0.011              4.861  
7                0.012              4.862  
8                0.034              3.201  
9                0.055              6.167  
10               0.076              4.477  
11               0.001              6.165  
12               0.015              5.402  
13               0.002              5.790  
14               5.055              8.413  
15               0.010              3.425  
16               0.011              5.593  
17               0.154              8.

In [3]:
data2 = preprocessing.scale(data1)
data2

array([[ 4.00006625, -1.55237099, -2.23010048, -2.21011424,  0.39189044,
         1.11678922,  2.70612314,  0.70139539,  2.23250653],
       [ 0.45332362,  1.59102855, -1.76020523,  1.73130327,  2.00838885,
         1.73606709,  1.78008863,  0.29082248,  2.34535363],
       [-0.19743905,  0.13496435,  0.60646231,  0.28934528,  0.1320887 ,
         0.17978524, -1.50793161,  3.47540799,  0.29936831],
       [ 0.48898097,  0.76978003, -1.24996775,  0.93245536,  0.99884995,
         0.09337438,  1.16878631,  0.52203429,  1.00746984],
       [ 0.29240306,  1.44707407, -2.20110451,  0.85406858,  3.39217824,
         2.66321137,  1.76560497, -0.31868782,  1.76511742],
       [-0.71345008,  2.41227708,  1.21405979,  1.19560556, -0.42140646,
        -0.94333444, -0.61063452, -0.47318175, -0.77127559],
       [-0.28162293, -0.49277159,  0.92192247, -0.35530575,  0.35253903,
        -0.94255896, -0.61109432, -0.47265267, -0.77113523],
       [-0.80013764,  1.51551145,  1.04804924,  1.09695897, -0

In [4]:
# 计算相关系数矩阵
data3 = np.around(np.corrcoef(data2.T),decimals=3)
data3

array([[ 1.   , -0.327, -0.714, -0.336,  0.309,  0.408,  0.79 ,  0.156,
         0.744],
       [-0.327,  1.   , -0.035,  0.644,  0.42 ,  0.255,  0.009, -0.078,
         0.094],
       [-0.714, -0.035,  1.   ,  0.07 , -0.74 , -0.755, -0.93 , -0.109,
        -0.924],
       [-0.336,  0.644,  0.07 ,  1.   ,  0.383,  0.069, -0.046, -0.031,
         0.073],
       [ 0.309,  0.42 , -0.74 ,  0.383,  1.   ,  0.734,  0.672,  0.098,
         0.747],
       [ 0.408,  0.255, -0.755,  0.069,  0.734,  1.   ,  0.658,  0.222,
         0.707],
       [ 0.79 ,  0.009, -0.93 , -0.046,  0.672,  0.658,  1.   , -0.03 ,
         0.89 ],
       [ 0.156, -0.078, -0.109, -0.031,  0.098,  0.222, -0.03 ,  1.   ,
         0.29 ],
       [ 0.744,  0.094, -0.924,  0.073,  0.747,  0.707,  0.89 ,  0.29 ,
         1.   ]])

In [5]:
# 计算特征值，特征向量
featValue, featVec=  np.linalg.eig(data3.T)
featValue, featVec

(array([4.66136245, 2.08940114, 1.04341574, 0.50677053, 0.31517892,
        0.19249378, 0.1147383 , 0.03114411, 0.04549504]),
 array([[ 0.34204349, -0.36798589, -0.05979351,  0.37387319, -0.35785918,
         -0.31193253, -0.55830139, -0.23070546,  0.11809174],
        [ 0.05732865,  0.61341613, -0.02776368, -0.15760294, -0.76102032,
          0.11089043, -0.03033182, -0.04649436, -0.01715246],
        [-0.44636057,  0.06618852,  0.09325357,  0.06824743, -0.04684918,
         -0.20714434, -0.46555989,  0.6903082 , -0.211311  ],
        [ 0.01940016,  0.60076072,  0.0366341 ,  0.59793163,  0.3075667 ,
         -0.39537511,  0.09554833, -0.14057002,  0.00614221],
        [ 0.37657748,  0.30678255, -0.01065209, -0.09592102,  0.39482157,
          0.50692974, -0.5812179 , -0.00749449, -0.06346108],
        [ 0.37940597,  0.12364808,  0.12227768, -0.62033791,  0.15534982,
         -0.63792048, -0.04502533,  0.07928678,  0.04001917],
        [ 0.43213441, -0.09198116, -0.24646488,  0.1472812

In [6]:
#求特征值的贡献度
gx = featValue/np.sum(featValue)
gx

array([0.51792916, 0.23215568, 0.11593508, 0.05630784, 0.03501988,
       0.0213882 , 0.0127487 , 0.00346046, 0.005055  ])

In [7]:
#选出主成分 k = 3 三个特征值贡献率相加>85
k = [0, 1, 2]
k

[0, 1, 2]

In [8]:
#选出主成分对应的特征向量矩阵
selectVec = np.matrix(featVec.T[k]).T
selectVe=selectVec*(-1)
selectVec

matrix([[ 0.34204349, -0.36798589, -0.05979351],
        [ 0.05732865,  0.61341613, -0.02776368],
        [-0.44636057,  0.06618852,  0.09325357],
        [ 0.01940016,  0.60076072,  0.0366341 ],
        [ 0.37657748,  0.30678255, -0.01065209],
        [ 0.37940597,  0.12364808,  0.12227768],
        [ 0.43213441, -0.09198116, -0.24646488],
        [ 0.09137538, -0.0696209 ,  0.94955147],
        [ 0.44638151, -0.01734033,  0.09031832]])

In [9]:
df1=data2*np.array(pd.DataFrame(selectVec).loc[:,0])
tf1=df1*gx[0]/100
pd.DataFrame(tf1,index=data1.index, columns=data1.columns).sort_values(["x1：人口密度(人/km2)"])

x1：人口密度(人/km2)  x 2：人均耕地面积(ha)  x 3：森林覆盖率(%)  x 4：农民人均纯收入(元/人)  \
样本序号                                                                   
12         -0.001746        0.000022     -0.001271         -0.000025   
8          -0.001417        0.000450     -0.002423          0.000110   
6          -0.001264        0.000716     -0.002807          0.000120   
13         -0.001250       -0.000122     -0.001031         -0.000028   
11         -0.001022       -0.000106      0.000625         -0.000245   
15         -0.001021        0.000009     -0.001720          0.000048   
14         -0.001011       -0.000271     -0.000674         -0.000062   
9          -0.000747       -0.000118     -0.001840         -0.000043   
10         -0.000613       -0.000139     -0.001521         -0.000040   
7          -0.000499       -0.000146     -0.002131         -0.000036   
16         -0.000390       -0.000249     -0.000753          0.000047   
3          -0.000350        0.000040     -0.001402          0.000029   
20          0.000128        0.000165      0.000068         -0.000066   
17          0.000153       -0.000244     -0.001098          0.000046   
21          0.000274       -0.000195      0.000784          0.000062   
5           0.000518        0.000430      0.005089          0.000086   
19          0.000697       -0.000289     -0.000117          0.000014   
18          0.000802       -0.000191      0.000108         -0.000064   
2           0.000803        0.000472      0.004069          0.000174   
4           0.000866        0.000229      0.002890          0.000094   
1           0.007086       -0.000461      0.005156         -0.000222   

      x 5：人均粮食产量 (kg/人)  x 6：经济作物占农作物播面比例(％)  x 7：耕地占土地面积比率(％)  \
样本序号                                                             
12            -0.001525            -0.002751         -0.001366   
8             -0.000644             0.000372         -0.002097   
6             -0.000822            -0.001854         -0.001367   
13            -0.001271            -0.001640         -0.001151   
11            -0.000808             0.000686         -0.000947   
15            -0.000919            -0.001206         -0.001846   
14            -0.001391             0.000602         -0.000515   
9             -0.001224             0.000047         -0.000795   
10            -0.000619             0.000356         -0.000555   
7              0.000688            -0.001852         -0.001368   
16            -0.000731            -0.002669         -0.001084   
3              0.000258             0.000353         -0.003375   
20            -0.001649             0.000318         -0.000480   
17            -0.000304            -0.001292         -0.000344   
21            -0.000422             0.002195          0.000227   
5              0.006616             0.005233          0.003952   
19            -0.000580            -0.001550          0.000597   
18            -0.001283            -0.001137         -0.000144   
2              0.003917             0.003411          0.003984   
4              0.001948             0.000183          0.002616   
1              0.000764             0.002195          0.006057   

      x 8：果园与林地面积之比(％)  x 9：灌溉田占耕地面积之比(％)  
样本序号                                       
12           -0.000223          -0.001608  
8            -0.000218          -0.002322  
6            -0.000224          -0.001783  
13           -0.000226          -0.001482  
11           -0.000226          -0.001360  
15           -0.000224          -0.002249  
14            0.001039          -0.000631  
9            -0.000213          -0.001359  
10           -0.000208          -0.001908  
7            -0.000224          -0.001783  
16           -0.000224          -0.001546  
3             0.001645           0.000692  
20           -0.000215          -0.000615  
17           -0.000188          -0.000537  
21           -0.000204          -0.000090  
5            -0.000151           0.004081  
19           -0.000209           0.000

In [10]:
df=data2*np.array(pd.DataFrame(selectVec).loc[:,0])+data2*np.array(pd.DataFrame(selectVec).loc[:,1])+data2*np.array(pd.DataFrame(selectVec).loc[:,2])
tf=df*gx/sum(gx[0:3])
pd.DataFrame(tf1,index=data1.index, columns=data1.columns).sort_values(["x1：人口密度(人/km2)","x 2：人均耕地面积(ha)","x 3：森林覆盖率(%)"])

x1：人口密度(人/km2)  x 2：人均耕地面积(ha)  x 3：森林覆盖率(%)  x 4：农民人均纯收入(元/人)  \
样本序号                                                                   
12         -0.001746        0.000022     -0.001271         -0.000025   
8          -0.001417        0.000450     -0.002423          0.000110   
6          -0.001264        0.000716     -0.002807          0.000120   
13         -0.001250       -0.000122     -0.001031         -0.000028   
11         -0.001022       -0.000106      0.000625         -0.000245   
15         -0.001021        0.000009     -0.001720          0.000048   
14         -0.001011       -0.000271     -0.000674         -0.000062   
9          -0.000747       -0.000118     -0.001840         -0.000043   
10         -0.000613       -0.000139     -0.001521         -0.000040   
7          -0.000499       -0.000146     -0.002131         -0.000036   
16         -0.000390       -0.000249     -0.000753          0.000047   
3          -0.000350        0.000040     -0.001402          0.000029   
20          0.000128        0.000165      0.000068         -0.000066   
17          0.000153       -0.000244     -0.001098          0.000046   
21          0.000274       -0.000195      0.000784          0.000062   
5           0.000518        0.000430      0.005089          0.000086   
19          0.000697       -0.000289     -0.000117          0.000014   
18          0.000802       -0.000191      0.000108         -0.000064   
2           0.000803        0.000472      0.004069          0.000174   
4           0.000866        0.000229      0.002890          0.000094   
1           0.007086       -0.000461      0.005156         -0.000222   

      x 5：人均粮食产量 (kg/人)  x 6：经济作物占农作物播面比例(％)  x 7：耕地占土地面积比率(％)  \
样本序号                                                             
12            -0.001525            -0.002751         -0.001366   
8             -0.000644             0.000372         -0.002097   
6             -0.000822            -0.001854         -0.001367   
13            -0.001271            -0.001640         -0.001151   
11            -0.000808             0.000686         -0.000947   
15            -0.000919            -0.001206         -0.001846   
14            -0.001391             0.000602         -0.000515   
9             -0.001224             0.000047         -0.000795   
10            -0.000619             0.000356         -0.000555   
7              0.000688            -0.001852         -0.001368   
16            -0.000731            -0.002669         -0.001084   
3              0.000258             0.000353         -0.003375   
20            -0.001649             0.000318         -0.000480   
17            -0.000304            -0.001292         -0.000344   
21            -0.000422             0.002195          0.000227   
5              0.006616             0.005233          0.003952   
19            -0.000580            -0.001550          0.000597   
18            -0.001283            -0.001137         -0.000144   
2              0.003917             0.003411          0.003984   
4              0.001948             0.000183          0.002616   
1              0.000764             0.002195          0.006057   

      x 8：果园与林地面积之比(％)  x 9：灌溉田占耕地面积之比(％)  
样本序号                                       
12           -0.000223          -0.001608  
8            -0.000218          -0.002322  
6            -0.000224          -0.001783  
13           -0.000226          -0.001482  
11           -0.000226          -0.001360  
15           -0.000224          -0.002249  
14            0.001039          -0.000631  
9            -0.000213          -0.001359  
10           -0.000208          -0.001908  
7            -0.000224          -0.001783  
16           -0.000224          -0.001546  
3             0.001645           0.000692  
20           -0.000215          -0.000615  
17           -0.000188          -0.000537  
21           -0.000204          -0.000090  
5            -0.000151           0.004081  
19           -0.000209           0.000